# Dockerfile
FROM php:8.2-apache

RUN apt-get update && apt-get upgrade -y

RUN apt update && apt install -y zlib1g-dev libpng-dev && rm -rf /var/lib/apt/lists/*
RUN apt update && apt install -y curl
RUN apt-get install -y libcurl4-openssl-dev
RUN docker-php-ext-install fileinfo
RUN docker-php-ext-install curl

#install openssl
RUN apt-get update &&\
    apt-get -y remove openssl &&\
    apt-get -y install build-essential zlib1g-dev &&\
    apt-get -q update && apt-get -qy install wget make &&\
    wget https://www.openssl.org/source/openssl-3.0.5.tar.gz &&\
    tar -xzvf openssl-3.0.5.tar.gz &&\
    cd openssl-3.0.5 &&\
    ./config --prefix=/usr/local/ssl --openssldir=/usr/local/ssl shared zlib &&\
    make &&\
    make install

RUN docker-php-ext-install openssl

# Install Postgre PDO
RUN apt-get install -y libpq-dev \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pdo pdo_pgsql pgsql

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY artifacts/000-default.conf /etc/apache2/sites-available/000-default.conf
COPY artifacts/start-apache.sh /usr/local/bin

RUN a2enmod rewrite

COPY sample-php-app /var/www
RUN chown -R www-data:www-data /var/www

#RUN chmod 755 /usr/local/bin/start-apache.sh

#CMD ["start-apache.sh"]

ENV SSH_PASSWD "root:Docker!"
RUN apt-get update \
        && apt-get install -y --no-install-recommends dialog \
        && apt-get update \
  && apt-get install -y --no-install-recommends openssh-server \
  && echo "$SSH_PASSWD" | chpasswd 

COPY artifacts/sshd_config /etc/ssh/

COPY artifacts/init.sh /usr/local/bin/

RUN chmod u+x /usr/local/bin/init.sh

EXPOSE 80 22

ENTRYPOINT ["/usr/local/bin/init.sh"]